### ISSUE TITLE
 Unable to sign up on Speaker Registration Form. 

### ISSUE THREAD

**Issue by ch3rr17** [sandiegojs/sdjs-speaker-pipeline#110]
**Describe the bug**
 Unable to sign up on Speaker Registration Form. 

**To Reproduce**
1. Open Developer Tools
2. Go to 'http://localhost:3000'
3. Click on 'SignUp'
4. Fill Out Form
5. Post Error in console log

**Expected behavior**
Successful SignUp

**Screenshots**

  1) take a screenshot 
      - http://localhost:3000/#/SignUp

**System Info (please complete the following information):**
 - Device: [e.g. Macbook Pro, iPhone6]
 - OS: [e.g. iOS, Android]
 - Browser: [e.g. chrome, firefox]
 - Version: [e.g. 22]

**Additional context**
Post Error in console log upon form submission. Although object seems to be passing through

Screenshot: https://screencast.com/t/NyNl5KLT

**Comment by BladeSe7en** [comment]
Part of this problem is not having a db connected to the project. Once you set up a local db, if you sign up as a speaker, it will successfully  add the speaker request to the db and it will show up in the admin dash under meetups. However, the talkSubmit action found in src/components/SignUp/SignUpActions.js will still throw two errors
`xhr.js:178 POST http://localhost:3000/api/talks/talkSubmit net::ERR_EMPTY_RESPONSE`
`createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16)
    at XMLHttpRequest.m.onerror (xhr.js:87)`
